### PR TITLE
2A-L2: In imshow(), can avoid np.clip in 

### PR DESCRIPTION
**Pull request by yogeshluthra**
We can avoid np.clip() in imshow() helper function, as follows:

```{python}
# Helper functions
def normalize_image(image):
    """normalize the image between 0-255 and setting data type=uint8"""
    minImg, maxImg = np.min(image)*1., np.max(image)*1.
    return (((image - minImg)/(maxImg-minImg))*255).astype(np.uint8)

def imshow(title, image):
    """normalize the image between 0-255 and then show"""
    print 'To show, first normalizing the image between 0-255 and then setting data type=uint8'
    image = normalize_image(image)
    cv2.imshow(title, image)
```

### CODE REVIEW

**Comment by pdvelez** [comment]
Mapping the image to 0 - 255 (like you show above same as cv2.normalize using MINMAX) is the right way to go to prevent data loss. However in order to mimic the results obtained in the lectures you must clip these values ignoring what is beyond the 0 and 255 limits. Hence the warning in the imshow function.

**Comment by yogeshluthra** [comment]
Hi Pedro,

You can get similar result as lectures using the aforementioned code. Following image confirms that (first time uploading an image to github comment. Hope it works!)

screen shot 2017-08-24 at 9 54 38 am

**Comment by pdvelez** [comment]
Notice that the noisy image has a higher brightness (the background is no longer predominantly black). This is the noisy image from the lectures:
screen shot 2017-08-24 at 12 21 09 pm

Here's the noisy image using np.clip:
screen shot 2017-08-24 at 12 25 26 pm

**Comment by yogeshluthra** [comment]
I see. Yeah with np.clip() it looks closer to lecture's.
I focused more on the final outcome. They looked similar.

Anyway, I will close the pull request. Thanks!

**Pull request closed without merging**
